[build]
  base = "apps/web"
  command = "npm install && npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- apps/web/"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "camera=*, microphone=*"
    Content-Security-Policy = "frame-src 'self' https://meet.jit.si https://*.8x8.vc https://*.jit.si"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
